# Generated by Django 6.0 on 2026-06-05 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='session_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
